{"errorMessage": "module 'os' has no attribute 'add_dll_directory'", "errorType": "AttributeError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n", "  File \"/var/task/scraper_lambda.py\", line 5, in <module>\n    from scraper.scrape_all_dates_full import scrape_all_dates_full\n", "  File \"/var/task/scraper/scrape_all_dates_full.py\", line 2, in <module>\n    import pandas as pd\n", "  File \"/var/task/pandas/__init__.py\", line 30, in <module>\n    _delvewheel_patch_1_8_2()\n", "  File \"/var/task/pandas/__init__.py\", line 14, in _delvewheel_patch_1_8_2\n    os.add_dll_directory(libs_dir)\n"]}